### ISSUE TITLE
Use sodium for node only.

### ISSUE THREAD

**Issue by davidlehn** [digitalbazaar/crypto-ld#11]
Using sodium-universal causes webpacked code to pull in ~90KB of unneeded code.  Currently the only use in browsers is for ed25519 key generation which is also in forge.  Could switch to non-universal sodium for node and just forge for browsers.

**Comment by mattcollier** [comment]
forge might also be made to use sodium-native where appropriate as with rsa.generateKeyPair.

**Comment by mattcollier** [comment]
Also, where does the 90K figure come from?  Here's the directory listing from unminified sodium-javascript package
```
matt@xxx:~/dev/crypto-ld/node_modules/sodium-javascript$ ls -latr
total 108
-rw-r--r--   1 matt matt    88 Nov 17  2017 test.js
-rw-r--r--   1 matt matt  1079 Nov 17  2017 LICENSE
-rw-r--r--   1 matt matt 44307 Nov 17  2017 index.js
-rw-r--r--   1 matt matt   657 Nov 17  2017 example.js
-rw-r--r--   1 matt matt   747 Nov 17  2017 crypto_stream.js
-rw-r--r--   1 matt matt  1293 Nov 17  2017 crypto_generichash.js
-rw-r--r--   1 matt matt   433 Nov 17  2017 crypto_shorthash.js
-rw-r--r--   1 matt matt   978 Nov 17  2017 README.md
-rw-r--r--   1 matt matt  1005 Nov 19  2017 randombytes.js
-rw-r--r--   1 matt matt  1575 Mar 19  2018 crypto_kdf.js
-rw-r--r--   1 matt matt  1879 Feb 18 15:44 package.json
drwxr-xr-x   2 matt matt  4096 Feb 18 15:44 .
drwxr-xr-x 532 matt matt 20480 Feb 18 15:45 ..
```

**Comment by davidlehn** [comment]
forge has zero dependencies now.  I'm unsure the wisdom of adding any dependencies at all much less a package that uses or builds native code.  That might be an epic disaster for those 5.7M(!) weekly indirect users.  Maybe better to just open issues on node itself to add features sodium is filling in for.

**Comment by davidlehn** [comment]
It's not just sodium-javascript itself.  Look at the sodium-javascript dependencies.  Webpack will pull in blake and sip and so on even though we don't use them at all.  Can switch the sodium-universal require() to sodium-native and compare the webpack output sizes of jsonld-signatures or similar.
