### ISSUE TITLE
Add API Ed25519KeyPair.publicKeyFromFingerprint

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/crypto-ld#16]
See the following for an example implementation:
https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/master/lib/voters.js#L146

We want the public key material from the fingerprint.

**Comment by dmitrizagidulin** [comment]
@mattcollier This is implemented for `Ed25519KeyPair` in PR #35 (though not using the `multicodec` and `multibase` libs).
I'm not sure if you'd like to close the issue for now, or leave it open (as a reminder at some point to upgrade the code to using multicodec/multibase libs (which might support more key types in the future, etc).

**Comment by mattcollier** [comment]
@dmitrizagidulin very nice.  I think we can close this then.  Using multibase/mulicodec libs are not a requirement.  There may event be browser compatibility issues with those libs.
