### ISSUE TITLE
Replace base64url package for something not using Node Buffers

### ISSUE THREAD

**Issue by dmitrizagidulin** [digitalbazaar/crypto-ld#2]
A note for the future, when refactoring this library for use in the browser. Currently, it uses `base64url` npm package, which depends on Node.js's Buffer (and so would require the use of the Buffer polyfill that Webpack provides). To avoid the heavy polyfill, need to replace it with something else (possibly the code from https://github.com/digitalbazaar/bedrock-web-private-remote-storage/issues/1)

**Comment by dlongley** [comment]
The code from jsonld-signatures could be moved here:

https://github.com/digitalbazaar/jsonld-signatures/blob/master/lib/util.js#L31-L62

And then jsonld-signatures can start using it here as a dependency.

**Comment by dmitrizagidulin** [comment]
@dlongley Yeah, agreed, working on moving that code to here.

**Comment by mattcollier** [comment]
this has been addressed by using base64url-universal@1

https://github.com/digitalbazaar/crypto-ld/commit/030e735684aa39f0ad65fa5cc33271035760ccca
