### ISSUE TITLE
Fix linting errors

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/crypto-ld#27]
There are several violations of the max-len 80 rule such as:

https://github.com/digitalbazaar/crypto-ld/blob/master/lib/Ed25519KeyPair.js#L15-L17

I addressed this in one file by using eslint-disable, but for some reason this trick doesn't work in the `Ed25519KeyPair.js` file.  When the eslint directives are put in place, the doc generation script no longer outputs a doc for this file.  

https://github.com/digitalbazaar/crypto-ld/blob/master/lib/RSAKeyPair.js#L30

What we really need is to figure out the syntax that would allow us to wrap these link lines so that we don't need the eslint-disable.

**Comment by dmitrizagidulin** [comment]
Closing this issue as fixed (the mentioned code has been rewritten and extracted in PR #47, and eslint is enabled and hooked up to CI).
