### ISSUE TITLE
Reimplement Ed25519.encrypt

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/crypto-ld#28]
This method needs updating.

https://github.com/digitalbazaar/crypto-ld/blob/master/lib/Ed25519KeyPair.js#L214

We have an implementation is another module that may need to be copied here, or perhaps that implementation should exist in some primitive module.

**Comment by dmitrizagidulin** [comment]
The `encrypt()` method has been removed as of version `v4.0.0` (none of our code has been using it anyway). Closing.
