### ISSUE TITLE
Remove sodium-native entirely

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/crypto-ld#37]
Apparently, there's no way for npm to create reproducible builds using package lock files and no optional dependencies, so we should remove `sodium-native` from the optional dependencies and use the node-forge implementation for old versions of node.js.

**Comment by mattcollier** [comment]
We're still working out the npm issues at this moment.

Whatever the case, it should be recognized what the performance implications of this are: https://github.com/digitalbazaar/crypto-bench

js ed25519 sign ~200 ops/sec vs sodium-native 4,787 ops/sec.

**Comment by mattcollier** [comment]
Using a version of npm that respects the --no-optional parameter address the immediate issue: https://github.com/npm/cli/pull/264.  The root of the issue was using an out of date docker node 12 alpine image with a version of npm prior to 6.12 which ships with node 12.13.1

**Comment by dmitrizagidulin** [comment]
@mattcollier Does that mean we should close this issue, or..?

**Comment by mattcollier** [comment]
I believe it can be closed but @dlongley submitted the issue, so I think we should hear from him on the matter.
