### ISSUE TITLE
 Error: Module did not self-register.

### ISSUE THREAD

**Issue by OR13** [digitalbazaar/crypto-ld#39]
```
.../node_modules/crypto-ld/node_modules/sodium-native/index.js:1
    Error: Module did not self-register.
        at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
```

Encountering this when attempting to use `http-signature-zcap-verify`...  Not sure exactly why.

**Comment by mattcollier** [comment]
sodium-native is a native nodejs module which involves a working c++ toolchain.  Can you or are you using Node 12?  If so, I suggest installing with `npm install --no-optional` which would not attempt to install/build sodium-native.

**Comment by mattcollier** [comment]
In the absence of sodium-native, Node crypto will be used if available otherwise it falls back to javascript implementation as in the browser.

**Comment by OR13** [comment]
I was using node 10, using node 12 worked but I get a couple console warnings... `DeprecationWarning: crypto.createDecipher is deprecated.` and `node_modules/borc/src/decoder.asm.js:1 Linking failure in asm.js: Unexpected stdlib member`... thanks for the pointer.

**Comment by mandyvenables** [comment]
Closing this because you found a workaround and there are no plans to add support for older versions of node at this time. Thanks for the report.
