### ISSUE TITLE
Refactor to remove bundling of Ed25519

### ISSUE THREAD

**Issue by OR13** [digitalbazaar/crypto-ld#40]
There should a package similar to: https://github.com/digitalbazaar/secp256k1-key-pair

It should handle testing of ed25519... then this package can focus on the LDKey interface.

Consumers should provide the key class, not a string, as is the case for jsonld-signatures and vc-js.

**Comment by OR13** [comment]
Note https://github.com/digitalbazaar/crypto-ld/pull/41#issuecomment-600325133

**Comment by dmitrizagidulin** [comment]
(Refactoring to extract bundled Ed25519 and RSA key pairs into their own repos, in progress.)

**Comment by dmitrizagidulin** [comment]
This has been addressed as of PR #47. Ed25519 or RSA related code is no longer bundled with this library; they have been removed to their own standalone repos.
Closing.
