### ISSUE TITLE
Add support for secp256k1

### ISSUE THREAD

**Issue by OR13** [digitalbazaar/crypto-ld#42]
Using https://github.com/digitalbazaar/secp256k1-key-pair

**Comment by mandyvenables** [comment]
https://github.com/digitalbazaar/crypto-ld/pull/41 was closed pending https://github.com/digitalbazaar/crypto-ld/pull/47, which will solve this issue.

**Comment by dmitrizagidulin** [comment]
This issue no longer applies (all bundled algorithms have been removed in PR #47). There is also now a tracking issue on the secp256k1 repo, to update its API to match the new `crypto-ld` API.

Closing.
