### ISSUE TITLE
 TypeError: Cannot read property 'modes' of undefined

### ISSUE THREAD

**Issue by OR13** [digitalbazaar/crypto-ld#46]
`/node_modules/x25519-key-pair/node_modules/node-forge/lib/aes.js:1`

**Comment by mattcollier** [comment]
@OR13 thanks for the report.  Can you provide a full stack trace?  What API was being called etc?

**Comment by OR13** [comment]
sorry, this is wrong repo, this is did key issue.

**Comment by OR13** [comment]
Moved here: https://github.com/digitalbazaar/did-method-key-js/issues/23
