### ISSUE TITLE
Generate keypair from seed?

### ISSUE THREAD

**Issue by iainphd** [digitalbazaar/crypto-ld#49]
Hi,

I have looked, and not found it, but just to be sure - is it possible to generate a keypair from a supplied seed? Similar to what can be seen at http://ed25519.herokuapp.com

Thanks - Iain

**Comment by mattcollier** [comment]
I think you're looking for this: https://github.com/digitalbazaar/crypto-ld/blob/master/lib/Ed25519KeyPair.js#L82

**Comment by iainphd** [comment]
Thank you, I had seen that actually but was confused by the comment "Generates a KeyPair with an optional deterministic seed" rather "from an optional deterministic seed"...

I'm afraid also confused by how to call it... is it something along the lines of:

`const options = {
  seed: "12345"
};

issuerKeyPair = await Ed25519KeyPair.from (options.seed);`

... that is not right, as its not populating the keyPair with values...

 { id: undefined,
  type: 'Ed25519VerificationKey2018',
  publicKeyBase58: undefined,
  privateKeyBase58: undefined }

**Comment by mattcollier** [comment]
You need to be calling the `generate` API not the `from` API: https://github.com/digitalbazaar/crypto-ld/blob/master/lib/Ed25519KeyPair.js#L87

and it will be...
```
issuerKeyPair = await Ed25519KeyPair.generate (options);`
```

**Comment by iainphd** [comment]
Thank you...

I got it working like this:

  seed = new Buffer(32)
  seed.write("12345", offset=0, length=seed.length-offset, encoding='utf8')
  const options = {
    seed
  };

  issuerKeyPair = await Ed25519KeyPair.generate (options);

**Comment by mattcollier** [comment]
Cool, you might consider `Buffer.from` https://nodejs.org/api/buffer.html#buffer_class_method_buffer_from_array

Closing.
