### ISSUE TITLE
Ready for release?

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/crypto-ld#5]
@dmitrizagidulin are we ready for a 1.0.0 release here?  Trying to clean up all the dev deps.

**Comment by dmitrizagidulin** [comment]
I'd do more like a v0.1.0 release, but yes! ready.

**Comment by mattcollier** [comment]
@dmitrizagidulin I haven't been doing releases below 1.0.0 because it limits our semver capabilities.  Please do a 1.0.0 release.

**Comment by dmitrizagidulin** [comment]
@mattcollier can you explain? Why is a 0.1.0 release for this lib limit semver capabilities?
(In general, I don't think the library is at a 1.0 stage yet, and won't be for a good while..)

**Comment by mattcollier** [comment]
A zero release is just not compatible with how we work: https://semver.org/#spec-item-4
We need to be able to use semver at all stages to track breaking changes etc.

For zero releases and NPM, ~ and ^ are functionally the same, so we lose resolution between new features and bug fixes.

**Comment by dmitrizagidulin** [comment]
But that's my point though.. I don't think the API is sufficiently stable yet.

**Comment by dmitrizagidulin** [comment]
@mattcollier I mean, ultimately I don't mind, we can release it at whatever version you'd like. :)
Just wanted to understand.

**Comment by mattcollier** [comment]
Well, maybe it's not ready for a release.  What are your concerts wrt stability?

**Comment by dmitrizagidulin** [comment]
I mean, it's definitely ready for a 0.1.0 release. My concerns are - these are just a guess at an appropriate API. We'll know more once it's in wider use, etc.

> so we lose resolution between new features and bug fixes

How come? Bug fixes are still patch releases, so 0.1.1 will be a bugfix, etc.

**Comment by mattcollier** [comment]
So, `0.2.0` is a feature release?  Which means that everywhere we're using this library we have to update the package file, which is what I'm looking to avoid.  We really want to be able to set  it and forget it in the dependent modules with ^1.0.0.  Unless of course there is a **breaking** change which would lead to a 2.0.0 release.

**Comment by dmitrizagidulin** [comment]
Published on npm as `1.0.0`, closing.
