### ISSUE TITLE
Add a fromKeyId() class method.

### ISSUE THREAD

**Issue by dmitrizagidulin** [digitalbazaar/crypto-ld#57]
* Takes a key id and a `documentLoader`
* Checks fetched document for the correct context supported by that crypto suite.
* Checks that the key is not revoked.

**Comment by dmitrizagidulin** [comment]
@mattcollier ah whoops, wrote the wrong name in my notes :) Changing.

**Comment by mattcollier** [comment]
Landed: https://github.com/digitalbazaar/crypto-ld/blob/master/CHANGELOG.md#510---2021-04-01
