### ISSUE TITLE
Deprecation / Maintenance Status

### ISSUE THREAD

**Issue by Laurin-W** [digitalbazaar/crypto-ld#67]
Is this library still being maintained? 
I'm implementing data integrity proofs for zcaps and I was having trouble to find what library is resposible for what part of the data integrity signing / verification procedure.
It did not seem to be very compatible with the data-integrity, eddsa-2022-cryptosuite, and jsonld-signatures libraries to me, and there haven't been code changes for 2 years.

Best, Laurin

**Comment by dlongley** [comment]
No, this library is not actively maintained and will likely be archived in the near future to make that more clear.

These repositories are relevant for data-integrity proofs:

https://github.com/digitalbazaar/data-integrity
https://github.com/digitalbazaar/jsonld-signatures
https://github.com/digitalbazaar/eddsa-rdfc-2022-cryptosuite
https://github.com/digitalbazaar/ecdsa-rdfc-2019-cryptosuite
https://github.com/digitalbazaar/ecdsa-sd-2023-cryptosuite
https://github.com/digitalbazaar/bbs-2023-cryptosuite
https://github.com/digitalbazaar/vc

The above use key libraries like these:

https://github.com/digitalbazaar/ed25519-multikey
https://github.com/digitalbazaar/ecdsa-multikey
https://github.com/digitalbazaar/bls12-381-multikey

And these libraries are additionally relevant for zcaps:

https://github.com/digitalbazaar/zcap
https://github.com/digitalbazaar/ezcap
https://github.com/digitalbazaar/ezcap-express
https://github.com/digitalbazaar/http-signature-zcap-invoke
https://github.com/digitalbazaar/http-signature-zcap-verify

**Comment by Laurin-W** [comment]
Thanks a lot for the overview, that was very helpful!

**Comment by dlongley** [comment]
You're welcome! I'm closing this one in favor of #68 now. Thanks for drawing attention to it.
