### ISSUE TITLE
Replace `chloride` dep with sodium-native/sodium-univeral

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/crypto-ld#9]
The chloride package is not being properly maintained.

This should resolve https://github.com/digitalbazaar/jsonld-signatures/issues/40 once `crypto-ld` is made a dependency of jsonld-signatures.

**Comment by mattcollier** [comment]
We want to use `sodium-native` and there are some implementation examples here: https://github.com/digitalbazaar/crypto-bench/blob/master/index.js#L163

**Comment by dlongley** [comment]
> maybe universal includes browser support?

It does, though we already need to pull forge in for RSA. In the future, we could replace what forge is doing with WebCrypto API and then use sodium-universal... unless there's yet another thing we need forge for that I'm unaware of.

**Comment by mattcollier** [comment]
For what it's worth, Node 10.x `crypto` can generate RSA keys.  So maybe we can fallback to forge in node < 10.x and remove ursa dep?

**Comment by dlongley** [comment]
> For what it's worth, Node 10.x crypto can generate RSA keys. So maybe we can fallback to forge in node < 10.x and remove ursa dep?

+1, let's do that.

**Comment by dmitrizagidulin** [comment]
Fixed in PR #7
